[tool.poetry]
name = "opendevin"
version = "0.1.0"
description = "OpenDevin: Code Less, Make More"
authors = ["OpenDevin"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/OpenDevin/OpenDevin"

[tool.poetry.dependencies]
python = "^3.10"
datasets = "^2.18.0"
pandas = "^2.2.1"
litellm = "^1.34.13"
termcolor = "^2.4.0"
seaborn = "^0.13.2"
docker = "^7.0.0"
fastapi = "^0.110.0"
toml = "^0.10.2"
uvicorn = "^0.29.0"
types-toml = "^0.10.8.20240310"
numpy = "^1.26.4"
json-repair = "^0.11.1"

[tool.poetry.group.langchain.dependencies]
langchain = "^0.1.13"
langchain-core = "^0.1.36"
langchain-community = "^0.0.29"

[tool.poetry.group.llama-index.dependencies]
llama-index = "^0.10.25"
llama-index-vector-stores-chroma = "^0.1.6"
chromadb = "^0.4.24"
llama-index-embeddings-huggingface = "^0.2.0"
llama-index-embeddings-azure-openai = "^0.1.6"
llama-index-embeddings-ollama = "^0.1.2"

[tool.poetry.group.dev.dependencies]
ruff = "^0.3.4"
mypy = "^1.9.0"
pre-commit = "^3.7.0"

[tool.poetry.group.test.dependencies]
pytest = "^8.1.1"

[[tool.poetry.source]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cpu"
priority = "primary"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"