[tool.poetry]
name = "openhands-ai"
version = "0.13.0"
description = "OpenHands: Code Less, Make More"
authors = ["OpenHands"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/All-Hands-AI/OpenHands"
packages = [
  { include = "openhands/**/*" }
]

[tool.poetry.dependencies]
python = "^3.12"
datasets = "2.15.0"
pandas = "2.1.3"
litellm = "^1.51.1"
google-generativeai = "0.3.2"
google-api-python-client = "2.111.0"
google-auth-httplib2 = "0.1.1"
google-auth-oauthlib = "1.1.0"
termcolor = "2.4.0"
seaborn = "0.13.0"
docker = "7.0.0"
fastapi = "0.104.1"
toml = "0.10.2"
uvicorn = "0.24.0"
types-toml = "0.10.8.7"
numpy = "1.26.2"
json-repair = "0.9.0"
browsergym = "0.10.2" # integrate browsergym as the browsing interface
html2text = "2.1.1"
e2b = "^0.17.1"
pexpect = "4.9.0"
jinja2 = "^3.1.3"
python-multipart = "0.0.6"
boto3 = "1.33.6"
minio = "^7.2.8"
gevent = "^24.2.1"
pyarrow = "14.0.1"
tenacity = "^8.5.0"
zope-interface = "6.1"
pathspec = "^0.12.1"
google-cloud-aiplatform = "1.36.4"
anthropic = {extras = ["vertex"], version = "0.8.1"}
grep-ast = "0.3.3"
tree-sitter = "0.21.3"
bashlex = "^0.18"
pyjwt = "^2.9.0"
dirhash = "0.2.1"
python-frontmatter = "^1.1.0"
python-docx = "1.1.0"
PyPDF2 = "3.0.1"
python-pptx = "0.6.22"
pylatexenc = "2.10"
tornado = "6.4"
python-dotenv = "1.0.0"
pylcs = "^0.1.1"
whatthepatch = "^1.0.6"
protobuf = "4.21.12"
opentelemetry-api = "1.25.0"
opentelemetry-exporter-otlp-proto-grpc = "1.25.0"
modal = "^0.64.145"
runloop-api-client = "0.7.0"
pygithub = "^2.5.0"

[tool.poetry.group.llama-index.dependencies]
llama-index = "0.9.15"
llama-index-vector-stores-chroma = "0.1.4"
chromadb = "0.4.22"
llama-index-embeddings-huggingface = "0.1.4"
torch = "2.1.1"
llama-index-embeddings-azure-openai = "0.1.4"
llama-index-embeddings-ollama = "0.1.4"

[tool.poetry.group.dev.dependencies]
ruff = "0.7.1"
mypy = "1.13.0"
pre-commit = "4.0.1"
build = "*"

[tool.poetry.group.test.dependencies]
pytest = "*"
pytest-cov = "*"
pytest-asyncio = "*"
pytest-forked = "*"
pytest-xdist = "*"
flake8 = "*"
openai = "*"
opencv-python = "*"
pandas = "*"
reportlab = "*"

[tool.coverage.run]
concurrency = ["gevent"]


[tool.poetry.group.runtime.dependencies]
jupyterlab = "*"
notebook = "*"
jupyter_kernel_gateway = "*"
flake8 = "*"
opencv-python = "*"


[build-system]
build-backend = "poetry.core.masonry.api"
requires = [
  "poetry-core",
]

[tool.autopep8]
# autopep8 fights with mypy on line length issue
ignore = [ "E501" ]

[tool.black]
# prevent black (if installed) from changing single quotes to double quotes
skip-string-normalization = true

[tool.ruff.lint]
select = ["D"]
# ignore warnings for missing docstrings
ignore = ["D1"]

[tool.ruff.lint.pydocstyle]
convention = "google"


[tool.poetry.group.evaluation.dependencies]
streamlit = "*"
whatthepatch = "*"
retry = "*"
evaluate = "*"
swebench = { git = "https://github.com/All-Hands-AI/SWE-bench.git" }
func_timeout = "*"
sympy = "*"
gdown = "*"
matplotlib = "*"
seaborn = "*"
tabulate = "*"

[tool.poetry-dynamic-versioning]
enable = true
style = "semver"

[tool.poetry.scripts]
openhands = "openhands.core.cli:main"
