name: Lint Frontend

on:
  pull_request:
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-lint.yml'
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-lint.yml'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: cd frontend && npm ci

      - name: Run TypeScript type checking
        run: cd frontend && npx tsc --noEmit

      - name: Run ESLint and Prettier
        run: cd frontend && npm run lint
